<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <groupId>SolaceQueueBrowserGui</groupId>
   <artifactId>SolaceQueueBrowserGui</artifactId>
   <version>1.0.0</version>
   <name>SolaceQueueBrowserGui</name>
   <description>GUI for browsing queues</description>
   <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
   </properties>
   <repositories>
      <repository>
         <id>local-repo</id>
         <url>file://${project.basedir}/lib</url>
      </repository>
   </repositories>
   <dependencies>
      <dependency>
         <groupId>org.json</groupId>
         <artifactId>json</artifactId>
         <version>20151123</version>
      </dependency>
      <dependency>
         <groupId>commons-cli</groupId>
         <artifactId>commons-cli</artifactId>
         <version>1.9.0</version>
      </dependency>
      <dependency>
         <groupId>commons-lang</groupId>
         <artifactId>commons-lang</artifactId>
         <version>2.6</version>
      </dependency>
      <dependency>
         <groupId>commons-logging</groupId>
         <artifactId>commons-logging</artifactId>
         <version>1.1.3</version>
      </dependency>
      <dependency>
         <groupId>com.google.code.gson</groupId>
         <artifactId>gson</artifactId>
         <version>2.2.2</version>
      </dependency>
      <dependency>
         <groupId>org.apache.logging.log4j</groupId>
         <artifactId>log4j-api</artifactId>
         <version>2.17.1</version>
      </dependency>
      <dependency>
         <groupId>org.apache.logging.log4j</groupId>
         <artifactId>log4j-core</artifactId>
         <version>2.17.1</version>
      </dependency>
      <dependency>
         <groupId>org.apache.logging.log4j</groupId>
         <artifactId>log4j-slf4j-impl</artifactId>
         <version>2.17.1</version>
      </dependency>
      <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp</artifactId>
         <version>3.12.2</version>
      </dependency>
      <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp-urlconnection</artifactId>
         <version>3.12.2</version>
      </dependency>
      <dependency>
         <groupId>com.squareup.okio</groupId>
         <artifactId>okio</artifactId>
         <version>1.15.0</version>
      </dependency>
      <dependency>
         <groupId>org.slf4j</groupId>
         <artifactId>slf4j-api</artifactId>
         <version>1.7.21</version>
      </dependency>
      <dependency>
         <groupId>com.solace</groupId>
         <artifactId>solace-messaging-client</artifactId>
         <version>1.4.0</version>
      </dependency>
      <dependency>
         <groupId>com.solacesystems</groupId>
         <artifactId>sol-common</artifactId>
         <version>10.6.4</version>
      </dependency>
      <dependency>
         <groupId>com.solacesystems</groupId>
         <artifactId>sol-jcsmp</artifactId>
         <version>10.21.0</version>
      </dependency>
   </dependencies>
   <build>
      <finalName>SolaceQueueBrowserGui-${project.version}</finalName>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>3.4.0</version>
            <configuration>
               <archive>
                  <manifest>
                     <mainClass>com.solace.psg.queueBrowser.gui.QueueBrowserMainWindow</mainClass>
                  </manifest>
               </archive>
               <descriptorRefs>
                  <descriptorRef>jar-with-dependencies</descriptorRef>
               </descriptorRefs>
            </configuration>
            <executions>
               <execution>
                  <phase>package</phase>
                  <goals>
                     <goal>single</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
            <configuration>
               <source>17</source>
               <target>17</target>
            </configuration>
         </plugin>
      </plugins>
      <sourceDirectory>src</sourceDirectory>
      <resources>
         <resource>
            <directory>src</directory>
            <excludes>
               <exclude>**/*.java</exclude>
            </excludes>
         </resource>
      </resources>
   </build>
</project>